### ISSUE TITLE
Mocha-PhantomJS

### ISSUE THREAD

**Issue by metaskills** [norfolkjs/local-projects#1]
- mocha-phantomjs
  - :coffee: :ghost: PhantomJS Runners for Mocha
  - https://github.com/metaskills/mocha-phantomjs
  - @metaskills

**Comment by tjwebb** [comment]
Awesome project. I think I actually was using this before I met you.

**Comment by metaskills** [comment]
I would have added more like SQL Server adapter and TinyTDS if that is OK? Can I have commitz?

**Comment by lynnaloo** [comment]
Add as many as you want! I also love Mocha-Phantom. It's good for testing React.js
